openapi: 3.1.0
info:
  title: 宿泊施設API
  version: "0.1.0"
paths:
  /hotels:
    get:
      summary: 宿泊施設一覧
      responses:
        '200':
          description: 宿泊施設一覧
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: 施設ID
                      example: 1
                    name:
                      type: string
                      description: 施設名
                      example: ホテルこうしゅうえん
                    address:
                      type: string
                      description: 住所
                      example: 輪島市塚田町３１−６
                    area:
                      $ref: '#/components/schemas/Area'
                      description: エリア
                      example: 輪島市
                    phoneNumber:
                      type: string
                      description: 電話番号
                      example: 0768-22-8888
                    largeBathType:
                      $ref: '#/components/schemas/LargeBathType'
                      description: 大浴場の有無
                      example: あり
                    mealType:
                      $ref: '#/components/schemas/MealType'
                      description: 食事の有無
                      example: 朝食・夕食あり
                    notes:
                      type: string
                      description: 備考
                      example: 古民家です。Wi-Fiあり。
                    rooms:
                      type: array
                      description: 部屋一覧
                      items:
                        type: object
                        properties:
                          id:
                            type: integer
                            description: 部屋ID
                            example: 1
                          name:
                            type: string
                            description: 部屋名
                            example: 部屋A
                          capacity:
                            type: integer
                            description: 収容人数
                            example: 4
                          size:
                            type: string
                            description: 広さ
                            example: "50"
                          allowSingleUse:
                            type: boolean
                            description: 1人利用OKか
                            example: true
                          bathType:
                            $ref: '#/components/schemas/LargeBathType'
                            description: 風呂の有無
                            example: 浴槽付き
                          notes:
                            type: string
                            description: 備考
                            example: 現在風呂が使えません。
                          availability:
                            type: array
                            description: 空き状況
                            items:
                              type: object
                              properties:
                                date:
                                  type: string
                                  description: 日付
                                  example: 2024-09
                                status:
                                  type: array
                                  description: 空き状況
                                  items:
                                    type: integer
                                    enum: [0, 1, 2]
                                    example: 1
  /hotels/{hotelId}/rooms/{roomId}/availability:
    put:
      summary: 空き状況登録
      parameters:
        - name: hotelId
          in: path
          description: ホテルID
          schema:
            type: integer
        - name: roomId
          in: path
          description: 部屋ID
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                date:
                  type: string
                  example: "2024-09-01"
                status:
                  type: integer
                  enum: [0, 1, 2]
                  example: 1
components:
  schemas:
    Area:
      type: string
      enum:
        - 輪島市
        - 珠洲市
        - 穴水町
        - 能登町
        - 七尾市
        - 志賀町
    MealType:
      type: string
      enum:
        - 朝食・夕食あり
        - 朝食のみ
        - 夕食のみ
        - なし
    LargeBathType:
      type: string
      enum:
        - あり
        - なし
        - 問い合わせ
    BathType:
      type: string
      enum:
        - 浴槽付き
        - シャワーのみ
        - なし
