openapi: 3.1.0
info:
  title: 宿泊施設API
  version: "0.1.0"
paths:
  /accommodations_A:
    get:
      tags:
        - A案：一覧画面と詳細画面を分けない
      summary: 宿泊施設一覧取得
      parameters:
        - name: id
          in: path
          required: true
          description: 宿泊施設ID
          schema:
            type: integer
        - name: month
          in: query
          required: true
          description: 該当月（yyyy-MM形式）
          schema:
            type: string
            example: '2024-09'
      responses:
        '200':
          description: 宿泊施設一覧
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: 施設ID
                      example: 1
                    name:
                      type: string
                      description: 施設名
                      example: ホテルこうしゅうえん
                    address:
                      type: string
                      description: 住所
                      example: 輪島市塚田町３１−６
                    area:
                      $ref: '#/components/schemas/Area'
                      description: エリア
                      example: 輪島市
                    phoneNumber:
                      type: string
                      description: 電話番号
                      example: 0768-22-8888
                    hasLargeBath:
                      type: boolean
                      description: 大浴場の有無
                      example: true
                    mealType:
                      $ref: '#/components/schemas/MealType'
                      description: 食事の有無
                      example: 朝食・夕食あり
                    notes:
                      type: string
                      description: 備考
                      example: 古民家です。Wi-Fiあり。
                    rooms:
                      type: array
                      description: 部屋一覧
                      items:
                        type: object
                        properties:
                          id:
                            type: integer
                            description: 部屋ID
                            example: 1
                          name:
                            type: string
                            description: 部屋名
                            example: 部屋A
                          capacity:
                            type: integer
                            description: 収容人数
                            example: 4
                          sizeSquareMeters:
                            type: integer
                            description: 広さ（平米）
                            example: 50
                          notes:
                            type: string
                            description: 備考
                            example: 現在風呂が使えません。
                          availabilities:
                            type: array
                            description: 該当月全日の空き状況
                            items:
                              $ref: '#/components/schemas/RoomAvailability'
                            example: [ 予約可, 予約不可, 予約可, 予約可, 要確認, ... ]
  /accommodations_B:
    get:
      tags:
        - B案：一覧画面と詳細画面を分ける
      summary: 宿泊施設一覧取得
      responses:
        '200':
          description: 宿泊施設一覧
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: 施設ID
                      example: 1
                    name:
                      type: string
                      description: 施設名
                      example: ホテルこうしゅうえん
                    address:
                      type: string
                      description: 住所
                      example: 輪島市塚田町３１−６
                    area:
                      $ref: '#/components/schemas/Area'
                      description: エリア
                      example: 輪島市
                    phoneNumber:
                      type: string
                      description: 電話番号
                      example: 0768-22-8888
                    hasLargeBath:
                      type: boolean
                      description: 大浴場の有無
                      example: true
                    mealType:
                      $ref: '#/components/schemas/MealType'
                      description: 食事の有無
                      example: 朝食・夕食あり
                    notes:
                      type: string
                      description: 備考
                      example: 古民家です。Wi-Fiあり。

  /accommodations/{id}:
    get:
      tags:
        - B案：一覧画面と詳細画面を分ける
      summary: 宿泊施設詳細取得
      description: 現状ただの一件取得であるため、一覧APIにID検索用のパラメータを追加すればこのAPIは不要
      parameters:
        - name: id
          in: path
          required: true
          description: 施設ID
          schema:
            type: integer
      responses:
        '200':
          description: 指定されたIDの宿泊施設情報
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: 施設ID
                    example: 1
                  name:
                    type: string
                    description: 施設名
                    example: ホテルこうしゅうえん
                  address:
                    type: string
                    description: 住所
                    example: 輪島市塚田町３１−６
                  area:
                    $ref: '#/components/schemas/Area'
                    description: エリア
                    example: 輪島市
                  phoneNumber:
                    type: string
                    description: 電話番号
                    example: 0768-22-8888
                  hasLargeBath:
                    type: boolean
                    description: 大浴場の有無
                    example: true
                  mealType:
                    $ref: '#/components/schemas/MealType'
                    description: 食事の有無
                    example: 朝食・夕食あり
                  notes:
                    type: string
                    description: 備考
                    example: 古民家です。Wi-Fiあり。

  /accommodations/{id}/rooms:
    get:
      tags:
        - B案：一覧画面と詳細画面を分ける
      summary: 部屋情報取得
      parameters:
        - name: id
          in: path
          required: true
          description: 宿泊施設ID
          schema:
            type: integer
        - name: month
          in: query
          required: true
          description: 該当月（yyyy-MM形式）
          schema:
            type: string
            example: '2024-09'
      responses:
        '200':
          description: 部屋の予約状況
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: 部屋ID
                      example: 1
                    name:
                      type: string
                      description: 部屋名
                      example: 部屋A
                    capacity:
                      type: integer
                      description: 収容人数
                      example: 4
                    sizeSquareMeters:
                      type: integer
                      description: 広さ（平米）
                      example: 50
                    notes:
                      type: string
                      description: 備考
                      example: 現在風呂が使えません。
                    availabilities:
                      type: array
                      description: 該当月全日の空き状況
                      items:
                        $ref: '#/components/schemas/RoomAvailability'
                      example: [予約可, 予約不可, 予約可, 予約可, 要確認, ...]
components:
  schemas:
    Area:
      type: string
      enum:
        - 輪島市
        - 珠洲市
        - 穴水町
        - 能登町
        - 七尾市
        - 志賀町
    MealType:
      type: string
      enum:
        - 朝食・夕食あり
        - 朝食のみ
        - 夕食のみ
        - なし
    RoomAvailability:
      type: string
      enum:
        - 予約可
        - 予約不可
        - 要確認
